Add stateful `compressor`, `expander`, `compander` combinators to `Protocols.Df`
clash-lang/clash-protocols pull request #82
Opened 2024-06-15 20:42 UTC by wyager

2024-06-26 13:04 UTC, martijnbastiaan commented
Sorry for the delay, I was out sick. Could you:

 * [Rebase on top of `origin/main`](https://git-scm.com/docs/git-rebase)
 * Squash your commit message into something informative
 * Add tests for your functions in [`Tests.Protocols.Df`](https://github.com/clash-lang/clash-protocols/blob/main/tests/Tests/Protocols/Df.hs)

?

2024-06-26 13:04 UTC, martijnbastiaan requested changes
Sorry for the delay, I was out sick. Could you:

 * [Rebase on top of `origin/main`](https://git-scm.com/docs/git-rebase)
 * Squash your commit message into something informative
 * Add tests for your functions in [`Tests.Protocols.Df`](https://github.com/clash-lang/clash-protocols/blob/main/tests/Tests/Protocols/Df.hs)

?

2024-07-02 07:38 UTC, martijnbastiaan approved these changes
Thank you! I'll leave this open for a bit in case any of the other maintainers have an opinion.

2024-07-15 13:43 UTC, merged

2024-07-16 12:04 UTC, gergoerdi commented on src/Protocols/Df.hs
> +compander s0 f = forceResetSanity |> Circuit (C.unbundle . go . C.bundle)
Could just use `mealyB` here directly